modLoader = "javafml"
loaderVersion = "[47,)"
license = "BSD-3-Clause-Clear"
[[mods]]
modId = "${mod_id}"
version = "1.0.11"
displayName = "PipeAPI"
authors = "The Duck Team"
description = '''PipeAPI for Extra Utilies Reborn Again and DuckTech'''
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
